# Generated by Django 4.0.4 on 2022-08-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_book_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='context',
            field=models.TextField(null=True),
        ),
    ]
