# Generated by Django 4.0.4 on 2022-08-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_book_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, default='a', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='context',
            field=models.TextField(),
        ),
    ]
