# Generated by Django 4.0.4 on 2022-08-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_book_slug_alter_book_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
